### ISSUE TITLE
screenshot in readme is disable

### ISSUE THREAD

**Issue by yassu** [deris/vim-shot-f#11]
I can't see screenshot in readme.
 I think this link is disable.

**Comment by deris** [comment]
Thanks for your comment.
I can't see screenshot too.
But I can't recover, because I don't have local backup of screenshot...

**Comment by yassu** [comment]
But now, readme does not work definitely.
So, I think you should do any of the following:

1. remake gif file (it is difficult?)
2. delete link to image

**Comment by deris** [comment]
Now it recovered.(but I do nothing)
I will change link to actual file later.
